# Generated by Django 4.2.5 on 2023-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильность'),
        ),
    ]
