# Generated by Django 4.2.5 on 2023-09-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_answers_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ответа')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильность')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anwers', to='testing.question', verbose_name='Связанный вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопрос',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
